### ISSUE TITLE
specific power

### ISSUE THREAD

**Issue by Zander10101** [emahon/war-thunder-display#2]
last 2 seconds, last 10 seconds, last 60 seconds, maybe last ten minutes?

**Comment by emahon** [comment]
General approach to calculating power:
- Take current energy
- Take energy n steps ago (where n = desired time interval / 250 ms)
- Subtract final from initial
- Divide by num seconds

Potential problems:
- May not be n measurements (easy enough to check)
- Measurement n steps ago may not be from same match (harder to check)
  - Can check that the plane is the same, which helps, but not a perfect solution... 
- Time between requests may not be exactly 250 ms (probably close enough for our purposes)

**Comment by emahon** [comment]
also add instantaneous power (divide by 250 ms)
